### PR TITLE
Move babel packages into devDependencies

### PR DESCRIPTION
**Pull request by vlasenko**

### CODE REVIEW

**Comment by saikat** [comment]
So the reason I did not do this is that babel is required for the build process, and when you deploy to Heroku, Heroku will build on its server using the production packages.  Is there a better standard way to handle this case?  Being able to deploy this package to Heroku easily is something I'd like to maintain.

**Comment by vlasenko** [comment]
That's interesting. I will look and think about this and let you know, if I come up with something better.

**Comment by vlasenko** [comment]
Alternative approach is to allow Heroku to install devDependencies via npm:
https://github.com/mbuchetics/heroku-buildpack-nodejs-grunt/issues/5

Seems concept of devDependencies is broken from the birth. Heroku thinks that devDependenices are used only during development, but not in production. While many JavaScript devs think that devDependencies are used during build, but not during runtime. 

It would be much more clean if there were package build dependencies and runtime-specific dependencies, dev, prod, etc, but things currently are the way they are...

**Comment by saikat** [comment]
Thanks!

**Pull request merged**
